const POLICY_TRANSLATIONS = {
    "pt-BR": {
        common_back: "Voltar ao Site",
        common_terms: "Terms of Use",
        common_moderation: "Moderation Policy",
        common_appeals: "Appeals Policy",
        common_privacy: "Privacy Policy",

        terms_title: "Hytale-Server-Guard | Terms of Use",
        terms_meta: "Terms of Use do Hytale Server Guard cobrindo escopo da plataforma, responsabilidade do usuário, direitos de moderação e princípios de safe harbor comunitário.",
        terms_kicker: "Compliance",
        terms_h1: "Terms of Use",
        terms_intro: "Estes termos posicionam o Hytale Server Guard como um registro moderado de incidentes e reports comunitários. O serviço não atua como tribunal, autoridade pública ou instância definitiva de culpa.",
        terms_s1_h: "1. Natureza da Plataforma",
        terms_s1_p1: "O Hytale Server Guard opera como um repositório moderado de player reports, incidentes de servidor e registros de watchlist submetidos por usuários e revisados por administradores. Os registros só são publicados após revisão humana e conforme padrões internos de moderação.",
        terms_s1_p2: "A publicação em plataforma não constitui conclusão jurídica final, decisão judicial ou declaração definitiva de culpa.",
        terms_s2_h: "2. Responsabilidade do Usuário",
        terms_s2_p: "Cada denunciante é responsável pela precisão, licitude e boa-fé das informações submetidas. É proibido enviar alegações fabricadas, maliciosas, fraudulentas, difamatórias ou intencionalmente enganosas.",
        terms_s2_l1: "Reports devem ser acompanhados de evidência.",
        terms_s2_l2: "Denúncias falsas, retaliatórias ou maliciosas são proibidas.",
        terms_s2_l3: "Usuários não podem se passar por terceiros nem manipular provas para induzir erro.",
        terms_s3_h: "3. Direito de Moderação e Edição",
        terms_s3_p: "A plataforma reserva-se o direito, a seu critério e conforme suas políticas, de revisar, rejeitar, editar, limitar, remover, arquivar ou suprimir registros submetidos e materiais relacionados.",
        terms_s3_l1: "rejeitar denúncias sem padrão mínimo de evidência",
        terms_s3_l2: "editar registros para clareza, neutralidade ou conformidade",
        terms_s3_l3: "remover materiais contestados enquanto estiverem em revisão",
        terms_s3_l4: "suspender ou encerrar contas abusivas",
        terms_s3_l5: "preservar logs internos de moderação para auditoria",
        terms_s4_h: "4. Nunca Publicar Automaticamente",
        terms_s4_p: "Nenhuma denúncia é publicada automaticamente. Todo registro passa por moderação humana antes de se tornar visível no Incident Registry ou na Moderated Watchlist.",
        terms_s5_h: "5. Cláusula de Safe Harbor Comunitário",
        terms_s5_p: "O Hytale Server Guard atua como intermediador de conteúdo submetido por usuários e reserva-se o direito de revisar, restringir ou remover materiais contestados, incompletos ou incompatíveis com seus padrões internos.",
        terms_s6_h: "6. Abuso do Sistema",
        terms_s6_p: "O uso da plataforma para assédio, retaliação, denúncias falsas ou escalada maliciosa pode resultar em suspensão de conta, remoção de conteúdo, bloqueio de novos envios e outras restrições de acesso.",
        terms_aside_kicker: "Princípios-base",
        terms_aside_pill1: "Evidência Obrigatória",
        terms_aside_pill2: "Revisão Humana",
        terms_aside_pill3: "Linguagem Neutra",
        terms_aside_pill4: "Direito de Apelação",
        terms_aside_h1: "Regra Operacional",
        terms_aside_p1: "Na área pública, prefira expressões como “reportado por”, “incidente registrado” e “alegação submetida”. Evite linguagem acusatória ou rótulos definitivos.",
        terms_aside_h2: "Políticas Relacionadas",

        moderation_title: "Hytale-Server-Guard | Moderation Policy",
        moderation_meta: "Moderation Policy do Hytale Server Guard definindo categorias de report, requisitos de evidência, revisão humana e critérios de rejeição.",
        moderation_kicker: "Padrões de Moderação",
        moderation_h1: "Moderation Policy",
        moderation_intro: "Esta política define o que pode ser reportado, o padrão mínimo de prova e os critérios de revisão aplicados antes que qualquer registro apareça publicamente em Player Reports ou na Moderated Watchlist.",
        moderation_s1_h: "1. O que Pode Ser Reportado",
        moderation_s1_p: "A plataforma pode revisar envios relacionados a condutas prejudiciais em servidores comunitários de Hytale, incluindo, sem limitação:",
        moderation_s1_l1: "griefing e destruição deliberada de bens ou estruturas",
        moderation_s1_l2: "uso de exploits ou abuso de mecânicas não autorizadas",
        moderation_s1_l3: "tentativas de scam, fraude ou conduta enganosa em trocas",
        moderation_s1_l4: "hacks, cheats ou modificações não autorizadas",
        moderation_s1_l5: "ban evasion e reentrada após sanções do servidor",
        moderation_s1_l6: "outras condutas que afetem materialmente a segurança do servidor",
        moderation_s2_h: "2. Requisitos de Evidência",
        moderation_s2_p: "Toda submissão precisa conter material de apoio claro. Um report sem prova não é elegível para publicação.",
        moderation_s2_l1: "evidência é obrigatória para revisão",
        moderation_s2_l2: "links precisam ser acessíveis e razoavelmente verificáveis",
        moderation_s2_l3: "as alegações devem ser consistentes com o material enviado",
        moderation_s2_l4: "o registro deve identificar jogador, servidor e contexto do incidente",
        moderation_s3_h: "3. Processo de Revisão Humana",
        moderation_s3_p: "Nenhuma denúncia é publicada automaticamente. Cada envio passa por revisão humana antes de qualquer visibilidade pública.",
        moderation_s3_l1: "triagem inicial de integridade e completude",
        moderation_s3_l2: "revisão de evidências e consistência",
        moderation_s3_l3: "ajuste de neutralidade e redação quando necessário",
        moderation_s3_l4: "aprovação, rejeição ou retenção para esclarecimento adicional",
        moderation_s4_h: "4. Critérios de Rejeição",
        moderation_s4_p: "Moderadores devem reprovar ou suprimir registros que não atendam ao padrão mínimo. A rejeição pode ocorrer quando o envio for:",
        moderation_s4_l1: "sem prova",
        moderation_s4_l2: "com prova ambígua, fraca ou insuficiente",
        moderation_s4_l3: "duplicado sem elementos novos relevantes",
        moderation_s4_l4: "feito em má fé ou com intuito de assédio",
        moderation_s4_l5: "difamatório ou excessivamente acusatório",
        moderation_s4_l6: "inconsistente com as evidências apresentadas",
        moderation_s5_h: "5. Recomendação de Auditoria Interna",
        moderation_s5_p: "Para compliance e tratamento de disputas, a plataforma deve reter a denúncia original, as provas, a justificativa da aprovação e os logs operacionais de moderação.",
        moderation_aside_h1: "Regras Obrigatórias",
        moderation_aside_l1: "Nunca publicar sem prova.",
        moderation_aside_l2: "Nunca publicar automaticamente.",
        moderation_aside_l3: "Sempre preferir linguagem neutra.",
        moderation_aside_h2: "Terminologia Recomendada",
        moderation_aside_p2: "Prefira termos como Incident Registry, Player Reports e Moderated Watchlist. Evite rótulos dramáticos ou conclusivos.",

        appeals_title: "Hytale-Server-Guard | Appeals Policy",
        appeals_meta: "Appeals Policy do Hytale Server Guard cobrindo revisão, contestação, correção e remoção com base em novos elementos.",
        appeals_kicker: "Direitos de Revisão",
        appeals_h1: "Appeals Policy",
        appeals_intro: "Jogadores identificados em um registro listado podem solicitar revisão, correção, esclarecimento ou remoção quando houver novos elementos ou imprecisões materiais.",
        appeals_s1_h: "1. Direito de Solicitar Revisão",
        appeals_s1_p: "Um jogador listado pode solicitar nova revisão de um registro publicado ou não publicado. A contestação pode questionar exatidão factual, contexto, identificação do jogador, qualidade da prova ou manutenção pública do registro.",
        appeals_s2_h: "2. Tipos de Pedido de Apelação",
        appeals_s2_l1: "revisão das evidências originalmente consideradas",
        appeals_s2_l2: "correção de nomes, UUIDs, datas ou referências de servidor",
        appeals_s2_l3: "envio de material novo, contextual ou exculpatório",
        appeals_s2_l4: "pedido de remoção por erro, duplicidade ou disputa resolvida",
        appeals_s3_h: "3. Fluxo Básico de Apelação",
        appeals_s3_l1: "identificar o registro ou incidente específico",
        appeals_s3_l2: "explicar a razão da contestação em termos factuais e neutros",
        appeals_s3_l3: "fornecer novas provas ou esclarecimentos, quando existirem",
        appeals_s3_l4: "aguardar revisão humana e retorno da moderação",
        appeals_s3_p: "A plataforma pode solicitar informações complementares antes de decidir.",
        appeals_s4_h: "4. Possíveis Resultados",
        appeals_s4_l1: "manutenção do registro sem alteração",
        appeals_s4_l2: "correção ou restrição do escopo do registro",
        appeals_s4_l3: "ocultação temporária enquanto a revisão prossegue",
        appeals_s4_l4: "remoção da área pública ou exclusão interna, quando justificável",
        appeals_s5_h: "5. Padrão de Neutralidade",
        appeals_s5_p: "Apelações são tratadas como matéria de moderação, não como julgamento judicial. O resultado não deve ser comunicado como prova definitiva de inocência ou culpa.",
        appeals_aside_h1: "O que Ajuda na Revisão",
        appeals_aside_l1: "identificador específico do caso",
        appeals_aside_l2: "explicação clara do ponto incorreto",
        appeals_aside_l3: "novos prints, logs ou contexto de servidor",
        appeals_aside_l4: "evidência de identidade equivocada ou duplicidade",
        appeals_aside_h2: "Proteção contra Abuso",
        appeals_aside_p2: "Se a apelação demonstrar uso fabricado ou malicioso do sistema, a conta denunciante original pode sofrer restrição, remoção ou sanções adicionais.",

        privacy_title: "Hytale-Server-Guard | Privacy Policy",
        privacy_meta: "Privacy Policy do Hytale Server Guard cobrindo dados de conta, denúncias, uso de localStorage, registros de moderação e pedidos de revisão ou remoção.",
        privacy_kicker: "Tratamento de Dados",
        privacy_h1: "Privacy Policy",
        privacy_intro: "Esta política explica quais informações são coletadas, como são usadas para moderação e operação de contas, e como usuários podem solicitar correção, revisão ou remoção quando apropriado.",
        privacy_s1_h: "1. Dados Coletados",
        privacy_s1_p: "A plataforma pode coletar dados de conta e de denúncias necessários para operar um registro moderado de incidentes.",
        privacy_s1_l1: "dados de conta como nome, email, tipo de conta e servidor vinculado, quando aplicável",
        privacy_s1_l2: "dados da denúncia, incluindo descrição do incidente, prints, links de prova, nomes de jogador, UUIDs e metadados relacionados",
        privacy_s1_l3: "metadados de moderação, como resultado da revisão, horários e justificativas internas",
        privacy_s2_h: "2. Uso de localStorage",
        privacy_s2_p: "O front-end pode usar localStorage para continuidade de sessão, preferências simples da interface e estados leves do navegador. O localStorage permanece no dispositivo do usuário e pode ser apagado a qualquer momento.",
        privacy_s3_h: "3. Finalidade do Tratamento",
        privacy_s3_l1: "operar contas e fluxos de login",
        privacy_s3_l2: "receber, revisar e moderar denúncias",
        privacy_s3_l3: "manter logs internos para integridade da moderação",
        privacy_s3_l4: "dar suporte a apelações, correções e revisão de conteúdo contestado",
        privacy_s4_h: "4. Informação Pública vs Interna",
        privacy_s4_p: "Nem todo dado enviado aparece publicamente. A plataforma pode ocultar a identidade do denunciante na área pública e preservar os registros internos para moderação, apelação e compliance.",
        privacy_s5_h: "5. Pedidos de Revisão e Remoção",
        privacy_s5_p: "Usuários podem solicitar revisão, correção ou remoção de registros específicos em caso de erro, duplicidade, identidade equivocada ou informação nova relevante. Esses pedidos são tratados pelas políticas de moderação e apelação.",
        privacy_s6_h: "6. Orientação de Retenção",
        privacy_s6_p: "Por razões operacionais e de resolução de disputas, a plataforma deve reter a denúncia original, as provas enviadas, a justificativa da decisão e os logs relacionados por período interno razoável, sujeito a revisão posterior.",
        privacy_aside_h1: "Baseline de Privacidade",
        privacy_aside_l1: "limitar exposição pública quando não for necessária",
        privacy_aside_l2: "reter evidências internas para auditoria e apelação",
        privacy_aside_l3: "evitar publicação de alegações sem prova",
        privacy_aside_h2: "Disclaimer Legal",
        privacy_aside_p2: "Os registros exibidos representam reports enviados por usuários e avaliados sob padrões de moderação. A visibilidade de um registro não representa conclusão legal ou factual definitiva de culpa."
    },
    "en": {
        common_back: "Back to Site",
        common_terms: "Terms of Use",
        common_moderation: "Moderation Policy",
        common_appeals: "Appeals Policy",
        common_privacy: "Privacy Policy",
        terms_title: "Hytale-Server-Guard | Terms of Use",
        terms_meta: "Terms of Use for Hytale Server Guard covering platform scope, user responsibility, moderation rights and community safe harbor principles.",
        terms_kicker: "Compliance",
        terms_h1: "Terms of Use",
        terms_intro: "These terms position Hytale Server Guard as a moderated incident registry and community reporting platform. The service does not act as a court, public authority, or definitive adjudicator of guilt.",
        terms_s1_h: "1. Nature of the Platform",
        terms_s1_p1: "Hytale Server Guard operates as a moderated repository of player reports, server incidents, and watchlist records submitted by users and reviewed by administrators. Records are published only after human review and according to internal moderation standards.",
        terms_s1_p2: "Publication on the platform does not constitute a final legal finding, judicial determination, or definitive declaration of guilt.",
        terms_s2_h: "2. User Responsibility",
        terms_s2_p: "Each reporting user is responsible for the accuracy, lawfulness, and good-faith basis of submitted information. Fabricated, malicious, fraudulent, defamatory, or intentionally misleading allegations are prohibited.",
        terms_s2_l1: "Reports must be supported by evidence.",
        terms_s2_l2: "False or retaliatory submissions are prohibited.",
        terms_s2_l3: "Users must not impersonate others or manipulate evidence to mislead review.",
        terms_s3_h: "3. Moderation and Editorial Rights",
        terms_s3_p: "The platform reserves the right, at its discretion and according to its policies, to review, reject, edit, limit, remove, archive, or suppress submitted records and related materials.",
        terms_s3_l1: "reject reports that do not meet minimum evidence standards",
        terms_s3_l2: "edit records for clarity, neutrality, or policy compliance",
        terms_s3_l3: "remove contested materials pending review",
        terms_s3_l4: "suspend or terminate abusive accounts",
        terms_s3_l5: "preserve internal moderation logs for audit purposes",
        terms_s4_h: "4. No Automatic Publication",
        terms_s4_p: "No report is published automatically. Every record is subject to human moderation before becoming visible in the public Incident Registry or Moderated Watchlist.",
        terms_s5_h: "5. Community Safe Harbor Clause",
        terms_s5_p: "Hytale Server Guard acts as an intermediary for user-submitted content and reserves the right to review, restrict, or remove contested, incomplete, or non-compliant materials.",
        terms_s6_h: "6. Abuse of the System",
        terms_s6_p: "Using the platform for harassment, retaliation, false reporting, or malicious escalation may result in suspension, content removal, denial of future submissions, and broader access restrictions.",
        terms_aside_kicker: "Core Principles",
        terms_aside_pill1: "Evidence Required",
        terms_aside_pill2: "Human Review",
        terms_aside_pill3: "Neutral Wording",
        terms_aside_pill4: "Appeal Rights",
        terms_aside_h1: "Operational Rule",
        terms_aside_p1: "In the public area, prefer expressions such as “reported by”, “incident recorded”, and “submission under review”. Avoid accusatory or definitive labels.",
        terms_aside_h2: "Related Policies",
        moderation_title: "Hytale-Server-Guard | Moderation Policy",
        moderation_meta: "Moderation Policy for Hytale Server Guard defining report categories, evidence requirements, human review, and rejection standards.",
        moderation_kicker: "Moderation Standards",
        moderation_h1: "Moderation Policy",
        moderation_intro: "This policy defines what may be reported, the minimum evidence threshold, and the review standards applied before any record appears publicly in Player Reports or the Moderated Watchlist.",
        moderation_s1_h: "1. What May Be Reported",
        moderation_s1_p: "The platform may review submissions related to harmful conduct in community-operated Hytale servers, including but not limited to:",
        moderation_s1_l1: "griefing and deliberate destruction of structures or assets",
        moderation_s1_l2: "use of exploits or unauthorized mechanics abuse",
        moderation_s1_l3: "scam attempts, fraud patterns, or deceptive trade behavior",
        moderation_s1_l4: "hacks, cheats, or unauthorized client modifications",
        moderation_s1_l5: "ban evasion and re-entry after server sanctions",
        moderation_s1_l6: "other conduct materially affecting server safety or trust",
        moderation_s2_h: "2. Evidence Requirements",
        moderation_s2_p: "Every submission must contain clear supporting material. A report without evidence is not eligible for publication.",
        moderation_s2_l1: "evidence is mandatory for review",
        moderation_s2_l2: "links must be accessible and reasonably verifiable",
        moderation_s2_l3: "allegations must be consistent with submitted material",
        moderation_s2_l4: "the record should identify the relevant player, server, and context",
        moderation_s3_h: "3. Human Review Process",
        moderation_s3_p: "No report is published automatically. Each submission undergoes human moderation before any public visibility is granted.",
        moderation_s3_l1: "initial intake and completeness screening",
        moderation_s3_l2: "evidence review and consistency assessment",
        moderation_s3_l3: "neutrality and wording adjustments where needed",
        moderation_s3_l4: "approval, rejection, or hold for clarification",
        moderation_s4_h: "4. Rejection Criteria",
        moderation_s4_p: "Moderators should reject or suppress records that do not meet the minimum standard. Rejection may apply where a submission is:",
        moderation_s4_l1: "unsupported by evidence",
        moderation_s4_l2: "based on weak, ambiguous, or insufficient proof",
        moderation_s4_l3: "duplicative without meaningful new elements",
        moderation_s4_l4: "submitted in bad faith or for harassment",
        moderation_s4_l5: "defamatory or excessively accusatory in wording",
        moderation_s4_l6: "inconsistent with the evidence shown",
        moderation_s5_h: "5. Internal Audit Recommendation",
        moderation_s5_p: "For compliance and dispute handling, the platform should retain the original report, submitted evidence, approval rationale, and operational moderation logs.",
        moderation_aside_h1: "Mandatory Rules",
        moderation_aside_l1: "Never publish without evidence.",
        moderation_aside_l2: "Never publish automatically.",
        moderation_aside_l3: "Always prefer neutral wording.",
        moderation_aside_h2: "Terminology Guidance",
        moderation_aside_p2: "Prefer terms such as Incident Registry, Player Reports, and Moderated Watchlist. Avoid dramatic or conclusive labels.",
        appeals_title: "Hytale-Server-Guard | Appeals Policy",
        appeals_meta: "Appeals Policy for Hytale Server Guard covering review, challenge, correction, and removal requests based on new information.",
        appeals_kicker: "Review Rights",
        appeals_h1: "Appeals Policy",
        appeals_intro: "Players identified in a listed record may request review, correction, clarification, or removal where new elements or material inaccuracies are presented.",
        appeals_s1_h: "1. Right to Request Review",
        appeals_s1_p: "A listed player may request a new review of a published or unpublished record. An appeal may challenge factual accuracy, context, player identity matching, evidence quality, or continued public visibility.",
        appeals_s2_h: "2. Types of Appeal Requests",
        appeals_s2_l1: "review of the evidence originally considered",
        appeals_s2_l2: "correction of names, UUIDs, dates, or server references",
        appeals_s2_l3: "submission of new contextual or exculpatory material",
        appeals_s2_l4: "request for removal based on error, duplication, or resolved dispute",
        appeals_s3_h: "3. Basic Appeals Flow",
        appeals_s3_l1: "identify the specific record or incident entry",
        appeals_s3_l2: "explain the reason for the challenge in neutral factual terms",
        appeals_s3_l3: "provide new evidence or clarification where available",
        appeals_s3_l4: "await human review and outcome notice",
        appeals_s3_p: "The platform may request additional information before making a decision.",
        appeals_s4_h: "4. Potential Outcomes",
        appeals_s4_l1: "record maintained without change",
        appeals_s4_l2: "record corrected or narrowed",
        appeals_s4_l3: "record temporarily hidden pending further review",
        appeals_s4_l4: "record removed from public view or deleted internally where justified",
        appeals_s5_h: "5. Neutrality Standard",
        appeals_s5_p: "Appeals are reviewed as moderation matters, not judicial findings. Results should not be framed as definitive proof of innocence or guilt.",
        appeals_aside_h1: "What Helps an Appeal",
        appeals_aside_l1: "specific case identifier",
        appeals_aside_l2: "clear explanation of what is inaccurate",
        appeals_aside_l3: "new screenshots, logs, or server context",
        appeals_aside_l4: "evidence of mistaken identity or duplication",
        appeals_aside_h2: "False Report Protection",
        appeals_aside_p2: "If an appeal shows malicious or fabricated use of the system, the original reporting account may face restriction, removal, or further moderation sanctions.",
        privacy_title: "Hytale-Server-Guard | Privacy Policy",
        privacy_meta: "Privacy Policy for Hytale Server Guard covering account data, reports, localStorage usage, moderation records, and review or removal requests.",
        privacy_kicker: "Data Handling",
        privacy_h1: "Privacy Policy",
        privacy_intro: "This policy explains what information is collected, how it is used for moderation and account operations, and how users may request correction, review, or removal where appropriate.",
        privacy_s1_h: "1. Data Collected",
        privacy_s1_p: "The platform may collect account and report-related data necessary to operate a moderated incident registry.",
        privacy_s1_l1: "account details such as name, email, role, and linked server name where applicable",
        privacy_s1_l2: "report submission data including incident descriptions, screenshots, proof links, player names, UUIDs, and related metadata",
        privacy_s1_l3: "moderation metadata such as review outcomes, timestamps, and internal rationale",
        privacy_s2_h: "2. localStorage Use",
        privacy_s2_p: "The front end may use localStorage for session continuity, lightweight UI preferences, and client-side state. localStorage remains on the user’s device and may be cleared by the user at any time.",
        privacy_s3_h: "3. Purpose of Processing",
        privacy_s3_l1: "operate accounts and sign-in flows",
        privacy_s3_l2: "receive, review, and moderate reports",
        privacy_s3_l3: "maintain internal logs for moderation integrity",
        privacy_s3_l4: "support appeals, corrections, and challenged content review",
        privacy_s4_h: "4. Public vs Internal Information",
        privacy_s4_p: "Not all submitted data is displayed publicly. The platform may hide reporter identity in the public area while preserving internal records for moderation, appeals, and compliance.",
        privacy_s5_h: "5. Review and Removal Requests",
        privacy_s5_p: "Users may request review, correction, or removal of specific records in cases of error, duplication, mistaken identity, or materially new information. These requests are handled under moderation and appeals procedures.",
        privacy_s6_h: "6. Retention Guidance",
        privacy_s6_p: "For operational and dispute-resolution reasons, the platform should retain the original report, submitted evidence, decision rationale, and related logs for a reasonable internal period, subject to later review.",
        privacy_aside_h1: "Privacy Baseline",
        privacy_aside_l1: "limit public exposure where unnecessary",
        privacy_aside_l2: "retain internal evidence for audit and appeals",
        privacy_aside_l3: "avoid publication of unsupported allegations",
        privacy_aside_h2: "Legal Disclaimer",
        privacy_aside_p2: "Records shown on the service represent user-submitted reports assessed under moderation standards. Visibility of a record does not represent a definitive legal or factual finding of guilt."
    },
    "es": {
        common_back: "Volver al Sitio",
        common_terms: "Terms of Use",
        common_moderation: "Moderation Policy",
        common_appeals: "Appeals Policy",
        common_privacy: "Privacy Policy",
        terms_title: "Hytale-Server-Guard | Terms of Use",
        terms_meta: "Terms of Use de Hytale Server Guard sobre alcance de la plataforma, responsabilidad del usuario, derechos de moderación y safe harbor comunitario.",
        terms_kicker: "Compliance",
        terms_h1: "Terms of Use",
        terms_intro: "Estos términos posicionan a Hytale Server Guard como un registro moderado de incidentes y reportes comunitarios. El servicio no actúa como tribunal, autoridad pública ni instancia definitiva de culpa.",
        terms_s1_h: "1. Naturaleza de la Plataforma",
        terms_s1_p1: "Hytale Server Guard opera como un repositorio moderado de player reports, incidentes de servidor y registros de watchlist enviados por usuarios y revisados por administradores. Los registros solo se publican tras revisión humana y conforme a estándares internos de moderación.",
        terms_s1_p2: "La publicación en la plataforma no constituye una conclusión jurídica final, determinación judicial ni declaración definitiva de culpa.",
        terms_s2_h: "2. Responsabilidad del Usuario",
        terms_s2_p: "Cada denunciante es responsable de la exactitud, licitud y buena fe de la información enviada. Se prohíben alegaciones fabricadas, maliciosas, fraudulentas, difamatorias o intencionalmente engañosas.",
        terms_s2_l1: "Los reports deben estar respaldados por pruebas.",
        terms_s2_l2: "Las denuncias falsas o retaliatorias están prohibidas.",
        terms_s2_l3: "Los usuarios no deben suplantar a terceros ni manipular pruebas para inducir error.",
        terms_s3_h: "3. Derecho de Moderación y Edición",
        terms_s3_p: "La plataforma se reserva el derecho, a su criterio y según sus políticas, de revisar, rechazar, editar, limitar, eliminar, archivar o suprimir registros y materiales relacionados.",
        terms_s3_l1: "rechazar reports que no cumplan el mínimo de evidencia",
        terms_s3_l2: "editar registros por claridad, neutralidad o cumplimiento",
        terms_s3_l3: "retirar materiales impugnados mientras estén en revisión",
        terms_s3_l4: "suspender o cerrar cuentas abusivas",
        terms_s3_l5: "preservar logs internos de moderación para auditoría",
        terms_s4_h: "4. Nunca Publicar Automáticamente",
        terms_s4_p: "Ningún report se publica automáticamente. Todo registro pasa por moderación humana antes de hacerse visible en el Incident Registry o en la Moderated Watchlist.",
        terms_s5_h: "5. Cláusula de Safe Harbor Comunitario",
        terms_s5_p: "Hytale Server Guard actúa como intermediario de contenido enviado por usuarios y se reserva el derecho de revisar, restringir o retirar materiales impugnados, incompletos o incompatibles con sus estándares internos.",
        terms_s6_h: "6. Abuso del Sistema",
        terms_s6_p: "El uso de la plataforma para acoso, represalia, denuncias falsas o escalada maliciosa puede resultar en suspensión de cuenta, eliminación de contenido, bloqueo de nuevos envíos y otras restricciones de acceso.",
        terms_aside_kicker: "Principios Base",
        terms_aside_pill1: "Evidencia Obligatoria",
        terms_aside_pill2: "Revisión Humana",
        terms_aside_pill3: "Lenguaje Neutral",
        terms_aside_pill4: "Derecho de Apelación",
        terms_aside_h1: "Regla Operativa",
        terms_aside_p1: "En el área pública, prefiera expresiones como “reportado por”, “incidente registrado” y “alegación enviada”. Evite etiquetas acusatorias o definitivas.",
        terms_aside_h2: "Políticas Relacionadas",
        moderation_title: "Hytale-Server-Guard | Moderation Policy",
        moderation_meta: "Moderation Policy de Hytale Server Guard que define categorías de report, requisitos de evidencia, revisión humana y criterios de rechazo.",
        moderation_kicker: "Estándares de Moderación",
        moderation_h1: "Moderation Policy",
        moderation_intro: "Esta política define qué puede reportarse, el umbral mínimo de evidencia y los criterios de revisión aplicados antes de que cualquier registro aparezca públicamente en Player Reports o en la Moderated Watchlist.",
        moderation_s1_h: "1. Qué Puede Reportarse",
        moderation_s1_p: "La plataforma puede revisar envíos relacionados con conductas perjudiciales en servidores comunitarios de Hytale, incluyendo pero sin limitarse a:",
        moderation_s1_l1: "griefing y destrucción deliberada de estructuras o bienes",
        moderation_s1_l2: "uso de exploits o abuso de mecánicas no autorizadas",
        moderation_s1_l3: "intentos de scam, fraude o conducta engañosa en intercambios",
        moderation_s1_l4: "hacks, cheats o modificaciones no autorizadas",
        moderation_s1_l5: "ban evasion y reingreso tras sanciones del servidor",
        moderation_s1_l6: "otras conductas que afecten materialmente la seguridad del servidor",
        moderation_s2_h: "2. Requisitos de Evidencia",
        moderation_s2_p: "Toda presentación debe contener material de apoyo claro. Un report sin pruebas no es elegible para publicación.",
        moderation_s2_l1: "la evidencia es obligatoria para la revisión",
        moderation_s2_l2: "los enlaces deben ser accesibles y razonablemente verificables",
        moderation_s2_l3: "las alegaciones deben ser consistentes con el material enviado",
        moderation_s2_l4: "el registro debe identificar jugador, servidor y contexto",
        moderation_s3_h: "3. Proceso de Revisión Humana",
        moderation_s3_p: "Ningún report se publica automáticamente. Cada envío pasa por moderación humana antes de recibir visibilidad pública.",
        moderation_s3_l1: "triage inicial de integridad y completitud",
        moderation_s3_l2: "revisión de evidencias y consistencia",
        moderation_s3_l3: "ajuste de neutralidad y redacción cuando sea necesario",
        moderation_s3_l4: "aprobación, rechazo o retención para aclaración adicional",
        moderation_s4_h: "4. Criterios de Rechazo",
        moderation_s4_p: "Los moderadores deben rechazar o suprimir registros que no cumplan el estándar mínimo. El rechazo puede aplicarse cuando el envío sea:",
        moderation_s4_l1: "sin pruebas",
        moderation_s4_l2: "con pruebas ambiguas, débiles o insuficientes",
        moderation_s4_l3: "duplicado sin elementos nuevos relevantes",
        moderation_s4_l4: "hecho de mala fe o con intención de acoso",
        moderation_s4_l5: "difamatorio o excesivamente acusatorio",
        moderation_s4_l6: "inconsistente con las evidencias presentadas",
        moderation_s5_h: "5. Recomendación de Auditoría Interna",
        moderation_s5_p: "Para compliance y resolución de disputas, la plataforma debe retener la denuncia original, las pruebas, la justificación de aprobación y los logs operativos de moderación.",
        moderation_aside_h1: "Reglas Obligatorias",
        moderation_aside_l1: "Nunca publicar sin pruebas.",
        moderation_aside_l2: "Nunca publicar automáticamente.",
        moderation_aside_l3: "Siempre preferir lenguaje neutral.",
        moderation_aside_h2: "Terminología Recomendada",
        moderation_aside_p2: "Prefiera términos como Incident Registry, Player Reports y Moderated Watchlist. Evite etiquetas dramáticas o concluyentes.",
        appeals_title: "Hytale-Server-Guard | Appeals Policy",
        appeals_meta: "Appeals Policy de Hytale Server Guard sobre revisión, corrección, contestación y remoción con base en nuevos elementos.",
        appeals_kicker: "Derechos de Revisión",
        appeals_h1: "Appeals Policy",
        appeals_intro: "Los jugadores identificados en un registro pueden solicitar revisión, corrección, aclaración o remoción cuando existan nuevos elementos o inexactitudes materiales.",
        appeals_s1_h: "1. Derecho a Solicitar Revisión",
        appeals_s1_p: "Un jugador listado puede solicitar una nueva revisión de un registro publicado o no publicado. La apelación puede cuestionar exactitud factual, contexto, identificación del jugador, calidad de la prueba o mantenimiento público del registro.",
        appeals_s2_h: "2. Tipos de Solicitud de Apelación",
        appeals_s2_l1: "revisión de la evidencia originalmente considerada",
        appeals_s2_l2: "corrección de nombres, UUIDs, fechas o referencias de servidor",
        appeals_s2_l3: "envío de material nuevo, contextual o exculpatorio",
        appeals_s2_l4: "solicitud de remoción por error, duplicidad o disputa resuelta",
        appeals_s3_h: "3. Flujo Básico de Apelación",
        appeals_s3_l1: "identificar el registro o incidente específico",
        appeals_s3_l2: "explicar la razón de la impugnación en términos neutrales y factuales",
        appeals_s3_l3: "aportar nuevas pruebas o aclaraciones, cuando existan",
        appeals_s3_l4: "esperar revisión humana y respuesta de la moderación",
        appeals_s3_p: "La plataforma puede solicitar información adicional antes de decidir.",
        appeals_s4_h: "4. Posibles Resultados",
        appeals_s4_l1: "mantenimiento del registro sin cambios",
        appeals_s4_l2: "corrección o reducción del alcance del registro",
        appeals_s4_l3: "ocultación temporal mientras la revisión continúa",
        appeals_s4_l4: "remoción del área pública o eliminación interna cuando sea justificable",
        appeals_s5_h: "5. Estándar de Neutralidad",
        appeals_s5_p: "Las apelaciones se revisan como materia de moderación, no como juicio judicial. El resultado no debe comunicarse como prueba definitiva de inocencia o culpa.",
        appeals_aside_h1: "Qué Ayuda en la Revisión",
        appeals_aside_l1: "identificador específico del caso",
        appeals_aside_l2: "explicación clara de qué es inexacto",
        appeals_aside_l3: "nuevos prints, logs o contexto del servidor",
        appeals_aside_l4: "evidencia de identidad equivocada o duplicidad",
        appeals_aside_h2: "Protección contra Abuso",
        appeals_aside_p2: "Si la apelación demuestra uso fabricado o malicioso del sistema, la cuenta denunciante original puede sufrir restricción, remoción o sanciones adicionales.",
        privacy_title: "Hytale-Server-Guard | Privacy Policy",
        privacy_meta: "Privacy Policy de Hytale Server Guard sobre datos de cuenta, denuncias, uso de localStorage, registros de moderación y solicitudes de revisión o remoción.",
        privacy_kicker: "Tratamiento de Datos",
        privacy_h1: "Privacy Policy",
        privacy_intro: "Esta política explica qué información se recopila, cómo se usa para moderación y operación de cuentas, y cómo los usuarios pueden solicitar corrección, revisión o remoción cuando corresponda.",
        privacy_s1_h: "1. Datos Recopilados",
        privacy_s1_p: "La plataforma puede recopilar datos de cuenta y de denuncias necesarios para operar un registro moderado de incidentes.",
        privacy_s1_l1: "datos de cuenta como nombre, email, tipo de cuenta y nombre de servidor vinculado, cuando corresponda",
        privacy_s1_l2: "datos de denuncias, incluyendo descripción del incidente, prints, enlaces de prueba, nombres de jugador, UUIDs y metadatos relacionados",
        privacy_s1_l3: "metadatos de moderación, como resultados de revisión, horarios y justificaciones internas",
        privacy_s2_h: "2. Uso de localStorage",
        privacy_s2_p: "El front-end puede usar localStorage para continuidad de sesión, preferencias ligeras de interfaz y estado del navegador. El localStorage permanece en el dispositivo del usuario y puede borrarse en cualquier momento.",
        privacy_s3_h: "3. Finalidad del Tratamiento",
        privacy_s3_l1: "operar cuentas y flujos de inicio de sesión",
        privacy_s3_l2: "recibir, revisar y moderar denuncias",
        privacy_s3_l3: "mantener logs internos para integridad de la moderación",
        privacy_s3_l4: "dar soporte a apelaciones, correcciones y revisión de contenido impugnado",
        privacy_s4_h: "4. Información Pública vs Interna",
        privacy_s4_p: "No toda la información enviada aparece públicamente. La plataforma puede ocultar la identidad del denunciante en el área pública y preservar registros internos para moderación, apelaciones y compliance.",
        privacy_s5_h: "5. Solicitudes de Revisión y Remoción",
        privacy_s5_p: "Los usuarios pueden solicitar revisión, corrección o remoción de registros específicos en casos de error, duplicidad, identidad equivocada o información nueva relevante. Estas solicitudes se manejan bajo las políticas de moderación y apelación.",
        privacy_s6_h: "6. Orientación de Retención",
        privacy_s6_p: "Por razones operativas y de resolución de disputas, la plataforma debe retener la denuncia original, las pruebas enviadas, la justificación de la decisión y los logs relacionados por un período interno razonable, sujeto a revisión posterior.",
        privacy_aside_h1: "Base de Privacidad",
        privacy_aside_l1: "limitar la exposición pública cuando no sea necesaria",
        privacy_aside_l2: "retener evidencias internas para auditoría y apelación",
        privacy_aside_l3: "evitar publicación de alegaciones sin pruebas",
        privacy_aside_h2: "Disclaimer Legal",
        privacy_aside_p2: "Los registros mostrados representan reports enviados por usuarios y evaluados bajo estándares de moderación. La visibilidad de un registro no representa una conclusión legal o factual definitiva de culpa."
    }
};

const POLICY_LANGUAGE_STORAGE_KEY = "hytaleguard_language";
let policyLanguage = detectPolicyLanguage();

function detectPolicyLanguage() {
    const stored = localStorage.getItem(POLICY_LANGUAGE_STORAGE_KEY);
    if (stored && POLICY_TRANSLATIONS[stored]) {
        return stored;
    }

    const browserLanguage = navigator.language || "pt-BR";
    if (browserLanguage.startsWith("es")) {
        return "es";
    }
    if (browserLanguage.startsWith("en")) {
        return "en";
    }
    return "pt-BR";
}

function pt(key) {
    return POLICY_TRANSLATIONS[policyLanguage]?.[key] || POLICY_TRANSLATIONS["pt-BR"]?.[key] || key;
}

function setPolicyLanguage(language) {
    if (!POLICY_TRANSLATIONS[language]) {
        return;
    }

    policyLanguage = language;
    localStorage.setItem(POLICY_LANGUAGE_STORAGE_KEY, language);
    applyPolicyTranslations();
}

function applyPolicyTranslations() {
    document.documentElement.lang = policyLanguage;

    const selector = document.getElementById("languageSelect");
    if (selector) {
        selector.value = policyLanguage;
    }

    document.querySelectorAll("[data-i18n]").forEach((element) => {
        const key = element.getAttribute("data-i18n");
        element.textContent = pt(key);
    });

    document.querySelectorAll("[data-i18n-html]").forEach((element) => {
        const key = element.getAttribute("data-i18n-html");
        element.innerHTML = pt(key);
    });

    document.querySelectorAll("[data-i18n-content]").forEach((element) => {
        const key = element.getAttribute("data-i18n-content");
        element.setAttribute("content", pt(key));
    });

    const titleKey = document.body.getAttribute("data-title-key");
    if (titleKey) {
        document.title = pt(titleKey);
    }
}

document.addEventListener("DOMContentLoaded", () => {
    applyPolicyTranslations();
    const selector = document.getElementById("languageSelect");
    if (selector) {
        selector.addEventListener("change", (event) => setPolicyLanguage(event.target.value));
    }
});
